---
title: "“Bilgi Yönetim Sistemleri - Bitirme Projesi Rapor : Esmanur Hurma 190401002 - Oğuz Kortun 200401099 - Fatmanur Ömerli 190401062 - Ceyda İncekara 210401008 - Sena Süyün 190401018 "
output: html_notebook
---
**Q1: İş Probleminin Tanımı**

WILUSA Bankası, müşteri tabanını genişletmek, müşteri memnuniyetini artırmak ve gelirlerini artırmak amacıyla bir müşteri pazarlama analizi gerçekleştirmektedir. Bu hedeflere ulaşmak için SuiteCRM platformunu kullanarak, müşteri verilerini toplamak, analiz etmek ve pazarlama stratejileri geliştirmek istemektedir. SuiteCRM, kullanıcı dostu arayüzü ve güçlü veri analizi özellikleriyle, müşteri ilişkilerini yönetmek ve pazarlama kampanyalarını optimize etmek için ideal bir araçtır.  Banka, SuiteCRM'in müşteri veri toplama, analiz ve kampanya yönetimi özelliklerini kullanarak, daha etkili ve özelleştirilmiş pazarlama stratejileri oluşturmayı planlamaktadır. Bu süreçte karşılaşılan zorluklar arasında müşteri verilerinin doğruluğunu ve güncelliğini sağlamak, veri analiz süreçlerinin karmaşıklığı ve rekabetçi pazarda etkili stratejiler geliştirmek yer almaktadır. Ancak, SuiteCRM'in sunduğu avantajlar ve otomatikleştirilmiş analiz süreçleri, bu zorlukların üstesinden gelmede bankaya önemli faydalar sağlayacaktır.

SuiteCRM platformu, WILUSA Bankası'nın iş süreçlerinde şu özelliklerden yararlanacaktır:
-Müşteri Verilerinin Toplanması: SuiteCRM, müşteri demografik ve finansal verilerinin kolayca toplanmasını ve merkezi bir veri tabanında saklanmasını sağlar.
-Veri Analizi: Platform, toplanan verilerin analiz edilmesi için gelişmiş araçlar sunar. Bu araçlar, pazarlama kampanyaları için değerli bilgiler elde edilmesini sağlar.
-Pazarlama Stratejilerinin Geliştirilmesi: SuiteCRM, analiz edilen veriler ışığında etkili pazarlama stratejilerinin geliştirilmesine yardımcı olur.
-Kampanya Yönetimi: Pazarlama kampanyalarının yönetimi ve müşterilere özel teklifler sunulması SuiteCRM üzerinden gerçekleştirilir.
-Sonuçların Değerlendirilmesi: Pazarlama kampanyalarının etkinliği izlenir ve analiz edilir. SuiteCRM, bu süreçleri otomatikleştirerek stratejilerin revize edilmesini kolaylaştırır.

Bu özellikler, WILUSA Bankası'nın müşteri ilişkilerini daha etkili bir şekilde yönetmesine ve pazarlama faaliyetlerini optimize etmesine olanak tanır. SuiteCRM'in sunduğu otomatikleştirilmiş süreçler ve gelişmiş analiz araçları, müşteri verilerinin doğru ve güncel tutulmasını, veri analiz süreçlerinin verimliliğini artırır ve rekabetçi pazarda daha etkili pazarlama stratejileri geliştirilmesine yardımcı olur.

**Q2: İş problemini çözmede kullanılacak data seti**
Kullandığımız veriyi bulduğumuz kaynak : _https://www.kaggle.com/_
Verisetinin linki : _https://www.kaggle.com/datasets/zain280/bank-customer-information-and-marketing-response_

Veri Formatı: Veri seti, CSV (Comma Separated Values) formatında sunulmaktadır.

Boyutu: Toplam 41.188 gözlem ve 21 değişken içermektedir.

Bu veri kümesi, banka müşterileri ve onların pazarlama kampanyalarına verdikleri yanıtlar hakkında bilgiler içerir. Veri seti müşterilerin yaş, iş, medeni durum, eğitim düzeyi, hesap bakiyesi gibi demografik ve finansal özelliklerini içeriyor. Ayrıca, vadeli mevduata abone olup olmadıkları (evet/hayır) ve pazarlama kampanyasının sonucu (başarı/başarısızlık) gibi pazarlama kampanyalarına verdikleri yanıtlara ilişkin bilgileri de içerir.

Veri kümesi, bir müşterinin vadeli mevduata abone olma kararını etkileyen faktörleri ve pazarlama kampanyalarının etkinliğini anlamaya yardımcı olmayı amaçlamaktadır.

_Ana Özellikler:_
Demografik bilgiler (age, job, marital status, education level)

Finansal bilgiler (account balance, housing loan, personal loan)

Pazarlama kampanyası bilgileri (campaign duration, number of contacts, outcome)

Pazarlama kampanyasına yanıt (subscription to term deposit, yes/no)

_Hedef Değişkeni_:

y (vadeli mevduat aboneliği, evet/hayır)

Örnek Sayısı:

5 (verilen örnekte)

_Nitelik Sayısı_:

16 (hedef değişken dahil)

Kullanılan veri seti aynıdır; sadece SuiteCRM platformunun zorunlu kıldığı "Name" sütununun eklenmesi gibi küçük bir değişiklik yapılmıştır. Bu sütun, müşteri verilerinin doğru bir şekilde yönetilmesi ve analiz edilmesi için gereklidir.
    
